export const SECOND = 1000;
export const MINUTE = SECOND * 60;
export const FIFTEEN_MINUTES = MINUTE * 15;
export const THIRTY_MINUTES = FIFTEEN_MINUTES * 2;
export const HOUR = MINUTE * 60;
export const DAY = HOUR * 24;
export const WEEK = DAY * 7;
export const MONTH = DAY * 30;
export const YEAR = DAY * 365;
